export const GET_PRODUCTS_FROM_DB = "GET_PRODUCTS_FROM_DB";
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PUT_PRODUCT_IN_EDIT_MODE = "PUT_PRODUCT_IN_EDIT_MODE";
export const MAKE_CHANGES_TO_PRODUCT = "MAKE_CHANGES_TO_PRODUCT";